### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by probonopd** [bildschirmtext/btx_decoder#9]
Please do a Linux version as well. Maybe using https://www.libsdl.org/, or is that overkill?

**Comment by Casandro** [comment]
Working on it, but can't push right now because I don't have the rights.

**Comment by mist64** [comment]
You should have the rights now.

**Comment by Casandro** [comment]
The "0.0.1" Version is pushed. It has a hardcoded connection (my server), and supports F1 for Initiator and F2 for Terminator.

**Comment by Casandro** [comment]
The SDL Version now has support for Umlauts and control characters. It's on a good start, so we could mark this issue as closed.
